author: Mario Lanza
avatar: /assets/10609708_672957986115083_7627741849738825230_n.png
baseurl: ''
collections:
  tabs:
    output: true
    sort_by: order
  cause:
    output: true
    sort_by: title
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      breadcrumb:
        -
          label: Home
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: index.html
    values:
      breadcrumb:
        -
          label: Home
description: Dedicated to all the IHS graduates and staff who have passed away throughout the years.
disqus:
  comments: true
  shortname: 'interlake-high-school-memorial-wall'
exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - docs
  - README.md
  - LICENSE
  - Rakefile
  - .tm_properties
github:
  username: MarioMangler
google_site_verification: 3aqd9Vsv-MOJpi9FCc0-AVfMeK2rAq4PAtwA0L689ng
img_cdn: ''
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
paginate: 25
permalink: /:categories/:title/
repository: Interlake-Saints/ihsmemorial.org
sass:
  sass_dir: /assets/css
  style: compressed
social:
  name: Mario Lanza
  email: MLanza1974@aol.com
  links:
    - https://twitter.com/MarioJLanza
    - https://github.com/MarioMangler
    - https://www.facebook.com/mariolanza
tagline: Dedicated to graduates and staff
theme_mode: dark
timezone: America/Los_Angeles
title: Interlake High School Memorial Wall
url: 'https://ihsmemorial.org'
toc: true
twitter:
  username: MarioJLanza
