title: The Late and Great of Interlake High School
email: MLanza1974@aol.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a site to notify those of us who attended Interlake High School of the classmates we've lost throughout the years. If you have any info that is accurate, or any pictures, please email me and I'll post them on the memorial wall.
  RIP to all of our lost and may we cherish their memories as is so deserved. May they never be forgotten.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MarioJLanza
github_username:  MarioMangler

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
