title: Interlake High School Memorial Wall
email: MLanza1974@aol.com
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated to all the IHS graduates and staff who have passed away throughout the years.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://interlake-saints.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MarioJLanza
github_username:  MarioMangler
show_excerpts: true
facebook_username: mariolanza

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
